/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SonicKnowledgeEntry = IDL.Record({
  'name' : IDL.Text,
  'content_type' : IDL.Text,
  'description' : IDL.Text,
  'highlights' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Profile = IDL.Record({
  'birthYear' : IDL.Nat,
  'name' : IDL.Text,
  'usageTimeRemaining' : IDL.Opt(IDL.Nat),
  'accountLocked' : IDL.Bool,
  'warnings' : IDL.Nat,
  'lastLogin' : Time,
});
export const PostContent = IDL.Record({
  'author' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const AgeCheckResult = IDL.Variant({
  'ok' : IDL.Null,
  'locked' : IDL.Null,
  'invalidInput' : IDL.Null,
  'tooOld' : IDL.Nat,
  'tooYoung' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSonicEntry' : IDL.Func([SonicKnowledgeEntry], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCommunityPost' : IDL.Func([IDL.Text], [], []),
  'getAllEntriesByType' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SonicKnowledgeEntry)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommunityPosts' : IDL.Func([], [IDL.Vec(PostContent)], ['query']),
  'getRemainingUsageTime' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Nat)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
  'getUsersByAge' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'issueWarning' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'searchSonicContent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SonicKnowledgeEntry)],
      ['query'],
    ),
  'setRemainingUsageTime' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'suggestSimilarEntries' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SonicKnowledgeEntry)],
      ['query'],
    ),
  'verifyAge' : IDL.Func([IDL.Text, IDL.Nat], [AgeCheckResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SonicKnowledgeEntry = IDL.Record({
    'name' : IDL.Text,
    'content_type' : IDL.Text,
    'description' : IDL.Text,
    'highlights' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Profile = IDL.Record({
    'birthYear' : IDL.Nat,
    'name' : IDL.Text,
    'usageTimeRemaining' : IDL.Opt(IDL.Nat),
    'accountLocked' : IDL.Bool,
    'warnings' : IDL.Nat,
    'lastLogin' : Time,
  });
  const PostContent = IDL.Record({
    'author' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const AgeCheckResult = IDL.Variant({
    'ok' : IDL.Null,
    'locked' : IDL.Null,
    'invalidInput' : IDL.Null,
    'tooOld' : IDL.Nat,
    'tooYoung' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSonicEntry' : IDL.Func([SonicKnowledgeEntry], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCommunityPost' : IDL.Func([IDL.Text], [], []),
    'getAllEntriesByType' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SonicKnowledgeEntry)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommunityPosts' : IDL.Func([], [IDL.Vec(PostContent)], ['query']),
    'getRemainingUsageTime' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Nat)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
    'getUsersByAge' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Profile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'issueWarning' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'searchSonicContent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SonicKnowledgeEntry)],
        ['query'],
      ),
    'setRemainingUsageTime' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'suggestSimilarEntries' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SonicKnowledgeEntry)],
        ['query'],
      ),
    'verifyAge' : IDL.Func([IDL.Text, IDL.Nat], [AgeCheckResult], []),
  });
};

export const init = ({ IDL }) => { return []; };