/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AgeCheckResult = { 'ok' : null } |
  { 'locked' : null } |
  { 'invalidInput' : null } |
  { 'tooOld' : bigint } |
  { 'tooYoung' : bigint };
export interface PostContent {
  'author' : Principal,
  'message' : string,
  'timestamp' : Time,
}
export interface Profile {
  'birthYear' : bigint,
  'name' : string,
  'usageTimeRemaining' : [] | [bigint],
  'accountLocked' : boolean,
  'warnings' : bigint,
  'lastLogin' : Time,
}
export interface SonicKnowledgeEntry {
  'name' : string,
  'content_type' : string,
  'description' : string,
  'highlights' : string,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSonicEntry' : ActorMethod<[SonicKnowledgeEntry], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCommunityPost' : ActorMethod<[string], undefined>,
  'getAllEntriesByType' : ActorMethod<[string], Array<SonicKnowledgeEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommunityPosts' : ActorMethod<[], Array<PostContent>>,
  'getRemainingUsageTime' : ActorMethod<[Principal], [] | [bigint]>,
  'getUserProfile' : ActorMethod<[Principal], Profile>,
  'getUsersByAge' : ActorMethod<[bigint, bigint], Array<Profile>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'issueWarning' : ActorMethod<[Principal, string], bigint>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'searchSonicContent' : ActorMethod<[string], Array<SonicKnowledgeEntry>>,
  'setRemainingUsageTime' : ActorMethod<[Principal, bigint], undefined>,
  'suggestSimilarEntries' : ActorMethod<[string], Array<SonicKnowledgeEntry>>,
  'verifyAge' : ActorMethod<[string, bigint], AgeCheckResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];