/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AgeCheckResult = { 'ok' : null } |
  { 'locked' : null } |
  { 'invalidInput' : null } |
  { 'tooOld' : bigint } |
  { 'tooYoung' : bigint };
export interface AppealRequest {
  'timestamp' : Time,
  'adminResponse' : [] | [string],
  'reason' : string,
}
export type AppealStatus = { 'pending' : AppealRequest } |
  { 'noAppeal' : null } |
  { 'denied' : AppealRequest } |
  { 'approved' : null };
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type ExternalBlob = Uint8Array;
export interface FriendRequest {
  'status' : string,
  'sentAt' : Time,
  'recipientId' : Principal,
  'requesterId' : Principal,
}
export interface FriendsModeRequest {
  'status' : string,
  'principal' : string,
  'birthdate' : string,
  'submittedAt' : bigint,
}
export interface Idea {
  'content' : string,
  'author' : string,
  'timestamp' : Time,
  'reviewed' : boolean,
}
export type ModeratorApplicationResult = { 'incorrectAnswers' : null } |
  { 'success' : null } |
  { 'applicationFull' : null };
export interface Password {
  'attemptsLeft' : bigint,
  'verified' : boolean,
  'password' : string,
}
export interface PostContent {
  'author' : Principal,
  'message' : string,
  'timestamp' : Time,
}
export interface Profile {
  'birthYear' : bigint,
  'password' : [] | [Password],
  'name' : string,
  'isSchoolAccount' : boolean,
  'usageTimeRemaining' : [] | [bigint],
  'accountLocked' : boolean,
  'warnings' : bigint,
  'lastLogin' : Time,
}
export interface SonicKnowledgeEntry {
  'name' : string,
  'content_type' : string,
  'description' : string,
  'highlights' : string,
}
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video { 'title' : string, 'blob' : ExternalBlob }
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSonicEntry' : ActorMethod<[SonicKnowledgeEntry], undefined>,
  'adminBanUser' : ActorMethod<[Principal], undefined>,
  'adminUnbanUser' : ActorMethod<[Principal], undefined>,
  'adminWarnUser' : ActorMethod<[Principal], undefined>,
  'applyForModerator' : ActorMethod<[string], ModeratorApplicationResult>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCommunityPost' : ActorMethod<[string], undefined>,
  'getAllEntriesByType' : ActorMethod<[string], Array<SonicKnowledgeEntry>>,
  'getAllFriendsModeRequests' : ActorMethod<[], Array<FriendsModeRequest>>,
  'getAllIdeas' : ActorMethod<[], Array<Idea>>,
  'getBanList' : ActorMethod<[], Array<Principal>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommunityPosts' : ActorMethod<[], Array<PostContent>>,
  'getFriendRequests' : ActorMethod<[], Array<FriendRequest>>,
  'getFriends' : ActorMethod<[], Array<Principal>>,
  'getFriendsModeStatus' : ActorMethod<[], [] | [string]>,
  'getMyVideos' : ActorMethod<[], Array<Video>>,
  'getRemainingUsageTime' : ActorMethod<[Principal], [] | [bigint]>,
  'getUserProfile' : ActorMethod<[Principal], Profile>,
  'getUsersByAge' : ActorMethod<[bigint, bigint], Array<Profile>>,
  'getWarnList' : ActorMethod<[], Array<Principal>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isCallerBanned' : ActorMethod<[], boolean>,
  'isSchoolAccount' : ActorMethod<[Principal], boolean>,
  'isUserModerator' : ActorMethod<[Principal], boolean>,
  'issueWarning' : ActorMethod<[Principal, string], bigint>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'markIdeaReviewed' : ActorMethod<[bigint], undefined>,
  'promoteUserToModerator' : ActorMethod<[Principal], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'respondToFriendRequest' : ActorMethod<[Principal, boolean], string>,
  'reviewAppeal' : ActorMethod<
    [Principal, boolean, [] | [string]],
    AppealStatus
  >,
  'reviewFriendsModeRequest' : ActorMethod<[string, string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'searchSonicContent' : ActorMethod<[string], Array<SonicKnowledgeEntry>>,
  'sendFriendRequest' : ActorMethod<[Principal], string>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setPassword' : ActorMethod<[string], undefined>,
  'setRemainingUsageTime' : ActorMethod<[Principal, bigint], undefined>,
  'setSchoolAccountMode' : ActorMethod<[Principal, boolean], undefined>,
  'submitBanAppeal' : ActorMethod<[string], AppealStatus>,
  'submitFriendsModeRequest' : ActorMethod<[string], undefined>,
  'submitIdea' : ActorMethod<[string], undefined>,
  'suggestSimilarEntries' : ActorMethod<[string], Array<SonicKnowledgeEntry>>,
  'uploadVideo' : ActorMethod<[string, ExternalBlob], undefined>,
  'verifyAge' : ActorMethod<[string, bigint], AgeCheckResult>,
  'verifyPassword' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];